const $=s=>document.querySelector(s), KEY='jiajia-purchase-v1';
let state={families:[],active:null},mode='quick',view='entry',editAction=null,deleteAction=null,timer,storageFailed=false;
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const raw=localStorage.getItem(KEY);if(raw){const d=JSON.parse(raw);if(!Array.isArray(d.families)||!d.families.every(f=>typeof f.id==='string'&&typeof f.name==='string'&&Array.isArray(f.items)&&f.items.every(i=>typeof i.id==='string'&&typeof i.text==='string')))throw Error('invalid');state=d;}}catch(e){storageFailed=true;$('#saveStatus').textContent='无法读取本地记录，请勿刷新或清除数据';}
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
if(!state.days||typeof state.days!=='object'||Array.isArray(state.days)){state.days={};state.selectedDate=localDate();state.days[state.selectedDate]={families:state.families,active:state.active};}
if(!validDate(state.selectedDate))state.selectedDate=localDate();
if(!state.days[state.selectedDate])state.days[state.selectedDate]={families:[],active:null};
state.families=state.days[state.selectedDate].families;state.active=state.days[state.selectedDate].active;
function syncDay(){state.days[state.selectedDate]={families:state.families,active:state.active};}
function renderDates(){$('#orderDate').value=state.selectedDate;$('#savedDates').innerHTML='<option value="">历史清单</option>'+Object.keys(state.days).filter(d=>state.days[d].families.length).sort().reverse().map(d=>`<option value="${d}">${d} · ${state.days[d].families.length} 家</option>`).join('');}
function changeDate(date){if(!validDate(date)){renderDates();return;}syncDay();state.selectedDate=date;const day=state.days[date]||{families:[],active:null};state.days[date]=day;state.families=day.families;state.active=day.active;$('#familyName').value='';$('#itemInput').value='';$('#parsePreview').textContent='';$('#quickName').value='';$('#quickQty').value='';updateQuick();render();save();if(view==='preview'){renderPrintChoices();makePreview();}}
function save(){syncDay();renderDates();try{if(storageFailed)throw Error('blocked');localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='已保存';}catch(e){$('#saveStatus').textContent='保存失败，请保持页面打开';toast('本地保存不可用，请勿关闭页面。');}}
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('#toast').hidden=true,3500);}
const current=()=>state.families.find(f=>f.id===state.active);
function setView(v){view=v;for(const n of ['entry','list','preview'])$('#'+n+'View').hidden=n!==v;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='preview'){renderPrintChoices();makePreview();}if(v==='list')renderAll();}
function render(){if(!current())state.active=state.families[0]?.id||null;$('#familyCount').textContent=state.families.length+' 家';const total=state.families.reduce((n,f)=>n+f.items.length,0);$('#totalBadge').textContent=total;$('#previewButton').disabled=!total;$('#familyList').innerHTML=state.families.map((f,i)=>`<article class="family ${f.id===state.active?'current':''}" draggable="true" data-id="${f.id}"><button class="family-select" data-action="select" data-id="${f.id}" ${f.id===state.active?'aria-current="true"':''}><span>${esc(f.name)}</span><small>${f.items.length} 条</small></button><div class="family-tools"><button data-action="up" data-id="${f.id}" ${i===0?'disabled':''} aria-label="上移${esc(f.name)}">上移</button><button data-action="down" data-id="${f.id}" ${i===state.families.length-1?'disabled':''} aria-label="下移${esc(f.name)}">下移</button><button data-action="delete" data-id="${f.id}" class="danger">删除</button></div></article>`).join('');const f=current();$('#activeName').textContent=f?.name||'采购清单';$('#renameFamily').hidden=!f;if(!f){$('#items').innerHTML='<p class="empty small">暂无商品</p>';$('#itemCount').textContent='0 条';}$('#customerHistory').innerHTML=(state.customerMemory||[]).map(n=>`<option value="${esc(n)}"></option>`).join('');$('#editorEmpty').hidden=!!f;$('#editorBody').hidden=!f;if(f){$('#activeName').textContent=f.name;$('#itemCount').textContent=f.items.length+' 条';$('#items').innerHTML=f.items.length?f.items.map((it,i)=>`<div class="item"><span class="index">${i+1}</span><span class="text">${esc(ListCore.display(it.text))}</span><details class="item-tools"><summary aria-label="商品操作">···</summary><div class="item-menu"><button data-item="${it.id}" data-action="up" ${i===0?'disabled':''} aria-label="上移${esc(ListCore.display(it.text))}">上移</button><button data-item="${it.id}" data-action="down" ${i===f.items.length-1?'disabled':''} aria-label="下移${esc(ListCore.display(it.text))}">下移</button><button data-item="${it.id}" data-action="edit">修改</button><button data-item="${it.id}" data-action="delete" class="danger">删除</button></div></details></div>`).join(''):'<p class="empty small">暂无商品</p>';}if(view==='list')renderAll();}
function renderAll(){syncDay();const dates=Object.keys(state.days).filter(d=>state.days[d].families.length).sort().reverse();$('#summary').textContent=`${dates.length} 天清单`;$('#allFamilies').innerHTML=dates.length?dates.map(date=>`<section class="day-section"><div class="day-heading"><h3>${date}</h3><button data-open-date="${date}">查看 / 录入</button><button data-print-date="${date}">打印</button></div><div class="day-families">${state.days[date].families.map(f=>`<article class="list-card"><h3>${esc(f.name)} <small class="muted">${f.items.length} 条</small></h3><ul>${f.items.map(i=>`<li>${esc(ListCore.display(i.text))}</li>`).join('')||'<li class="muted">暂无商品</li>'}</ul><button data-family="${f.id}" data-date="${date}">修改</button></article>`).join('')}</div></section>`).join(''):'<div class="empty">暂无清单</div>';}
function move(arr,index,delta){const to=index+delta;if(to<0||to>=arr.length)return;[arr[index],arr[to]]=[arr[to],arr[index]];save();render();}
function askDelete(text,fn){$('#deleteText').textContent=text;deleteAction=fn;$('#deleteDialog').showModal();}
function edit(title,label,value,fn){$('#dialogTitle').textContent=title;$('#editLabel').textContent=label;$('#editInput').value=value;editAction=fn;$('#editDialog').showModal();$('#editInput').focus();}
$('#familyForm').onsubmit=e=>{e.preventDefault();const name=$('#familyName').value.trim();if(!name)return;const f={id:uid(),name,items:[]};state.families.push(f);state.customerMemory=[name,...(state.customerMemory||[]).filter(n=>n!==name)].slice(0,100);state.active=f.id;$('#familyName').value='';save();render();if(mode!=='quick')$('#itemInput').focus();};
$('#familyList').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const index=state.families.findIndex(f=>f.id===b.dataset.id),f=state.families[index];if(!f)return;switch(b.dataset.action){case'select':state.active=f.id;save();render();break;case'up':move(state.families,index,-1);break;case'down':move(state.families,index,1);break;case'delete':askDelete(`删除“${f.name}”及其 ${f.items.length} 条商品？`,()=>{state.families.splice(index,1);render();save();});}};
let dragged=null;$('#familyList').ondragstart=e=>{const el=e.target.closest('.family');if(el){dragged=el.dataset.id;e.dataTransfer.setData('text/plain',dragged);e.dataTransfer.effectAllowed='move';}};$('#familyList').ondragover=e=>e.preventDefault();$('#familyList').ondrop=e=>{e.preventDefault();const target=e.target.closest('.family')?.dataset.id;if(!target||!dragged||target===dragged)return;const from=state.families.findIndex(f=>f.id===dragged),to=state.families.findIndex(f=>f.id===target);if(from<0||to<0)return;state.families.splice(to,0,state.families.splice(from,1)[0]);dragged=null;save();render();};
$('#renameFamily').onclick=()=>{const f=current();edit('修改家庭 / 客户名称','名称',f.name,s=>{f.name=s;});};
$('#items').onclick=e=>{const b=e.target.closest('[data-item]');if(!b)return;const f=current(),index=f.items.findIndex(i=>i.id===b.dataset.item),it=f.items[index];switch(b.dataset.action){case'up':move(f.items,index,-1);break;case'down':move(f.items,index,1);break;case'edit':edit('修改商品','商品和数量',it.text,s=>{const parsed=ListCore.parse(s);if(parsed.length!==1){toast('修改一条商品时，请只填一条。');return false;}it.text=parsed[0].text;rememberProducts(parsed);});break;case'delete':askDelete(`删除“${it.text}”？`,()=>{f.items.splice(index,1);save();render();});}};
$('#editForm').onsubmit=e=>{e.preventDefault();const text=$('#editInput').value.trim();if(!text)return;if(editAction(text)===false)return;$('#editDialog').close();save();render();};$('#cancelEdit').onclick=()=>$('#editDialog').close();$('#cancelDelete').onclick=()=>$('#deleteDialog').close();$('#confirmDelete').onclick=()=>{$('#deleteDialog').close();deleteAction?.();};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$('#quickForm').hidden=mode!=='quick';$('#itemForm').hidden=mode==='quick';$('#voiceHint').hidden=mode!=='batch';document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',x===b));$('#itemInput').rows=mode==='batch'?5:2;$('#itemInput').placeholder=mode==='batch'?'说或输入：黄瓜二斤、油菜半斤、豆腐五元':'例如：黄瓜二斤';$('#inputHelp').textContent=mode==='batch'?'逗号、顿号或换行均可分隔':'输入后按回车，接着记下一条';if(mode!=='quick')$('#itemInput').focus();});
$('#itemInput').oninput=()=>{const p=ListCore.parse($('#itemInput').value);$('#parsePreview').innerHTML=p.length?'<span>将加入：</span>'+p.map(x=>`<span class="${x.recognized?'':'unparsed'}">${esc(ListCore.display(x.text))}${x.recognized?'':'（请核对数量）'}</span>`).join('； '):'';};
$('#itemInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&mode==='single'){e.preventDefault();$('#itemForm').requestSubmit();}};
$('#itemForm').onsubmit=e=>{e.preventDefault();const f=current(),p=ListCore.parse($('#itemInput').value);if(!f||!p.length)return;f.items.push(...p.map(x=>({id:uid(),text:x.text})));rememberProducts(p);$('#itemInput').value='';$('#parsePreview').textContent='';save();render();toast(`已加入 ${p.length} 条商品`);$('#itemInput').focus();};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#allFamilies').onclick=e=>{const print=e.target.closest('[data-print-date]'),open=e.target.closest('[data-open-date]'),b=e.target.closest('[data-family]');if(print){changeDate(print.dataset.printDate);setView('preview');}else if(open){changeDate(open.dataset.openDate);setView('entry');}else if(b){changeDate(b.dataset.date);state.active=b.dataset.family;render();save();setView('entry');}};$('#previewButton').onclick=()=>setView('preview');$('#backEntry').onclick=$('#closePreview').onclick=()=>setView('entry');$('#printSize').onchange=makePreview;$('#printButton').onclick=()=>{makePreview();if(!$('#printButton').disabled)window.print();};
function groupNode(name,items,continued=false){const el=document.createElement('section');el.className='print-family';el.innerHTML=`<h3>${esc(name)}${continued?'（续）':''}</h3>`+items.map(i=>`<div class="print-row"><span class="print-label">${esc(ListCore.display(i.text))}</span><span class="handwrite"></span></div>`).join('');return el;}
function computeLayout(cols,font){const px=96/25.4,width=(paperSize().width-16-(cols-1)*3)/cols,limit=(paperSize().height-21)*px,gap=3*px;const measure=document.createElement('div');measure.className='paper measure';measure.style.cssText=`width:${width}mm;height:auto;padding:0;font-size:${font}pt;--row:${font>=14?8:7}mm`;document.body.append(measure);let pages=[[[]]],page=pages[0],col=0,used=0,bad=false;function next(){col++;used=0;if(col===cols){page=[];pages.push(page);col=0;}page[col]=[];}function get(name,items,cont){const el=groupNode(name,items,cont);el.querySelectorAll('.print-row').forEach(r=>r.style.minHeight=(font>=14?8:7)+'mm');measure.replaceChildren(el);const h=el.getBoundingClientRect().height+gap;for(const t of el.querySelectorAll('.print-label')){const r=document.createRange();r.selectNodeContents(t);const rects=[...r.getClientRects()];if(rects.some(x=>Math.abs(x.top-rects[0].top)>2))bad=true;}return {name,items,cont,h};}for(const f of printableFamilies()){let remaining=[...f.items],cont=false;while(remaining.length){let g=get(f.name,remaining,cont);if(g.h<=limit){if(used+g.h>limit)next();page[col].push(g);used+=g.h;break;}if(used)next();let lo=1,hi=remaining.length,best=0;while(lo<=hi){const mid=Math.floor((lo+hi)/2);const part=get(f.name,remaining.slice(0,mid),cont);if(part.h<=limit){best=mid;lo=mid+1;}else hi=mid-1;}if(!best){measure.remove();return null;}g=get(f.name,remaining.slice(0,best),cont);page[col].push(g);used=g.h;remaining=remaining.slice(best);cont=true;if(remaining.length)next();}}measure.remove();return {cols,font,pages,bad};}
function makePreview(){const size=paperSize();$('#pageStyle').textContent='@page{size:A4 '+$('#orientation').value+';margin:0}';const count=printableFamilies().reduce((n,f)=>n+f.items.length,0);$('#selectedCount').textContent=count+' 条';if(!count){$('#papers').innerHTML='<p class="empty">请选择要打印的内容</p>';$('#layoutInfo').textContent='未选择商品';$('#printButton').disabled=true;return;}const fonts=$('#printSize').value==='large'?[16,15,14]:[14,13,12];const candidates=[];for(const font of fonts)for(const cols of (size.width>210?[3,2,4,1]:[2,1,3])){const x=computeLayout(cols,font);if(x)candidates.push(x);}const valid=candidates.filter(x=>!x.bad),pool=valid.length?valid:candidates;if(!pool.length){$('#layoutInfo').textContent='内容过长，请缩短商品名称后重试';$('#printButton').disabled=true;return;}pool.sort((a,b)=>a.pages.length-b.pages.length||b.font-a.font||([2,1,3].indexOf(a.cols)-[2,1,3].indexOf(b.cols)));const best=pool[0];$('#papers').replaceChildren();best.pages.forEach((page,idx)=>{const paper=document.createElement('article');paper.className='paper';paper.style.width=size.width+'mm';paper.style.height=size.height+'mm';paper.style.fontSize=best.font+'pt';const content=document.createElement('div');content.className='paper-content';content.style.height=(size.height-21)+'mm';content.style.gridTemplateColumns=`repeat(${best.cols},minmax(0,1fr))`;for(let c=0;c<best.cols;c++){const column=document.createElement('div');column.className='paper-column';for(const g of page[c]||[]){const el=groupNode(g.name,g.items,g.cont);el.querySelectorAll('.print-row').forEach(r=>r.style.minHeight=(best.font>=14?8:7)+'mm');column.append(el);}content.append(column);}paper.append(content);const num=document.createElement('div');num.className='page-number';num.textContent=`${state.selectedDate} 采购清单 · 第 ${idx+1} / ${best.pages.length} 页`;paper.append(num);$('#papers').append(paper);});const n=count;$('#printButton').disabled=!n;$('#layoutInfo').textContent=`${n} 条商品 · ${best.pages.length} 页 A4 · ${best.cols} 列 · ${best.font} 磅字${best.bad?' · 超长内容已换行':''}`;scalePapers();}
function scalePapers(){const w=$('#paperViewport').clientWidth-16;for(const p of document.querySelectorAll('#papers .paper')){const scale=Math.min(1,w/p.offsetWidth);p.style.transform=`scale(${scale})`;p.style.transformOrigin='top center';p.style.marginBottom=-(p.offsetHeight*(1-scale))+'px';}}
window.addEventListener('resize',()=>{if(view==='preview')scalePapers();});window.addEventListener('beforeprint',()=>{if(view!=='preview')makePreview();});

const catalogs={常用:['黄瓜','油菜','香菜','胡萝卜','金针蘑','豆腐','土豆','西红柿','白菜','菠菜','生菜','芹菜','韭菜','茄子','青椒','鸡蛋','大葱','蒜','西兰花','白萝卜'],最近:[],叶菜:['白菜','菠菜','生菜','芹菜','韭菜','小白菜','大葱','蒜苗','茼蒿','油麦菜','娃娃菜','空心菜','小油菜','上海青','圆白菜','紫甘蓝'],瓜果根茎:['黄瓜','胡萝卜','土豆','西红柿','茄子','青椒','冬瓜','南瓜','白萝卜','山药','莲藕','红薯','芋头','莴笋','西葫芦','丝瓜','苦瓜','南瓜','秋葵','豇豆','扁豆'],菌菇蛋豆:['金针蘑','香菇','平菇','木耳','豆腐','豆干','鸡蛋','豆芽','杏鲍菇','口蘑','蟹味菇','海鲜菇','豆皮','腐竹','鸭蛋','鹌鹑蛋'],调料:['姜','蒜','大葱','小葱','辣椒','花椒','八角','香叶','盐','白糖','酱油','醋']};
const suggestedUnits={香菜:'两',金针蘑:'捆',豆腐:'元',胡萝卜:'个',冬瓜:'斤',鸡蛋:'斤'};let category='常用';
$('#categoryButtons').innerHTML=Object.keys(catalogs).map(c=>`<button type="button" data-category="${c}" aria-pressed="${c===category}">${c}</button>`).join('');
function productChoices(){const mem=[...state.productMemory];if(category==='最近')return mem.sort((a,b)=>b.lastUsed-a.lastUsed).map(x=>x.name).slice(0,30);if(category==='常用')return [...new Set([...mem.sort((a,b)=>b.count-a.count||b.lastUsed-a.lastUsed).map(x=>x.name),...catalogs.常用])].slice(0,24);return catalogs[category];}
function drawProducts(){$('#productButtons').innerHTML=productChoices().map(name=>`<button type="button" data-product="${esc(name)}" aria-pressed="${name===$('#quickName').value}">${esc(name)}</button>`).join('')||'<span class="muted">暂无记录</span>';}
$('#qtyButtons').innerHTML=['半','1','1.5','2','3','5'].map(n=>`<button type="button" data-qty="${n}" aria-pressed="false">${n}</button>`).join('')+'<button type="button" id="plusHalf" aria-label="数量加0.5">+0.5</button>';
$('#unitButtons').innerHTML=['','斤','两','个','捆','元'].map(n=>`<button type="button" data-unit="${n}" aria-pressed="${n===''}">${n||'不填'}</button>`).join('');
function updateQuick(){const name=$('#quickName').value.trim(),qty=$('#quickQty').value.trim(),unit=$('#quickUnit').value;$('#quickResult').textContent=name&&qty?ListCore.display(name+' '+ListCore.number(qty)+unit):'';document.querySelectorAll('[data-qty]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.qty===qty));document.querySelectorAll('[data-unit]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.unit===unit));document.querySelectorAll('[data-product]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.product===name));}
$('#categoryButtons').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.setAttribute('aria-pressed',x===b));drawProducts();};
$('#productButtons').onclick=e=>{const b=e.target.closest('[data-product]');if(!b)return;$('#quickName').value=b.dataset.product;$('#quickUnit').value=state.productMemory.find(x=>x.name===b.dataset.product)?.unit??'';updateQuick();};
$('#qtyButtons').onclick=e=>{if(e.target.closest('#plusHalf')){const raw=$('#quickQty').value.trim(),v=raw==='半'?0.5:Number(ListCore.number(raw));if(raw&&!/^(半|[零〇一二两三四五六七八九十百千点]+|\d+(?:\.\d+)?|\.\d+)$/.test(raw)||!Number.isFinite(v)){toast('请先填写有效数量');return;}$('#quickQty').value=String(Math.round((v+0.5)*1000000)/1000000);updateQuick();return;}const b=e.target.closest('[data-qty]');if(b){$('#quickQty').value=b.dataset.qty;updateQuick();}};
$('#unitButtons').onclick=e=>{const b=e.target.closest('[data-unit]');if(b){$('#quickUnit').value=b.dataset.unit;updateQuick();}};
for(const id of ['quickName','quickQty','quickUnit'])$('#'+id).addEventListener('input',updateQuick);
$('#quickForm').onsubmit=e=>{e.preventDefault();const f=current(),name=$('#quickName').value.trim(),qty=$('#quickQty').value.trim(),unit=$('#quickUnit').value;if(!f)return;if(!/^(半|[一二两三四五六七八九十百千零点]+|\d+(?:\.\d+)?|\.\d+)$/.test(qty)||qty==='0'){toast('请填写有效数量，例如 2、半、1.5');$('#quickQty').focus();return;}if(/[\n、，,；;]/.test(name)){toast('点选录入一次加一条，多条请用批量录入');return;}const parsed=ListCore.parse(name+' '+qty+unit)[0];f.items.push({id:uid(),text:parsed.text});rememberProducts([parsed]);save();render();$('#quickName').value='';$('#quickQty').value='';updateQuick();$('#quickName').focus();};
$('#exportData').onclick=()=>{syncDay();const blob=new Blob([JSON.stringify({...state,version:2},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='采购清单备份-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('备份已下载，请保管好文件');};
$('#importData').onclick=()=>$('#importFile').click();
$('#importFile').onchange=async()=>{const file=$('#importFile').files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error();const data=JSON.parse(await file.text());const source=data.days&&typeof data.days==='object'&&!Array.isArray(data.days)?data.days:{[state.selectedDate]:{families:data.families}};const imported={};for(const [date,day] of Object.entries(source)){if(!validDate(date)||!day||!Array.isArray(day.families)||!day.families.every(f=>typeof f.name==='string'&&Array.isArray(f.items)&&f.items.every(i=>typeof i.text==='string')))throw Error();imported[date]={families:day.families.map(f=>({id:uid(),name:f.name,items:f.items.map(i=>({id:uid(),text:i.text}))})),active:null};}const count=Object.values(imported).reduce((n,d)=>n+d.families.length,0);$('#deleteText').textContent=`按日期追加 ${count} 家清单，保留已有记录。`;$('#deleteDialog h2').textContent='导入备份';$('#confirmDelete').textContent='导入';deleteAction=()=>{syncDay();for(const [date,day] of Object.entries(imported)){if(!state.days[date])state.days[date]={families:[],active:null};state.days[date].families.push(...day.families);rememberProducts(day.families.flatMap(f=>f.items));state.customerMemory=[...new Set([...state.customerMemory,...day.families.map(f=>f.name)])].slice(0,100);}state.families=state.days[state.selectedDate].families;storageFailed=false;render();save();toast('已导入');};$('#deleteDialog').showModal();}catch{toast('无法读取备份，请选择有效备份文件');}finally{$('#importFile').value='';}};
$('#deleteDialog').addEventListener('close',()=>{$('#deleteDialog h2').textContent='确认删除？';$('#confirmDelete').textContent='删除';});

function rememberProducts(items){for(const item of items){const parsed=ListCore.parse(item.text)[0];if(!parsed)continue;const name=(parsed.name||parsed.text).trim();if(!name||name.length>100)continue;let rec=state.productMemory.find(x=>x.name===name);if(!rec){rec={name,count:0,lastUsed:0,unit:''};state.productMemory.push(rec);}rec.count++;rec.lastUsed=Date.now();if(parsed.recognized)rec.unit=parsed.unit;}state.productMemory=state.productMemory.sort((a,b)=>b.lastUsed-a.lastUsed).slice(0,300);drawProducts();}
state.productMemory=Array.isArray(state.productMemory)?state.productMemory.filter(x=>x&&typeof x.name==='string'&&Number.isFinite(x.count)&&Number.isFinite(x.lastUsed)&&typeof x.unit==='string'):[];
state.customerMemory=Array.isArray(state.customerMemory)?state.customerMemory.filter(x=>typeof x==='string'):state.families.map(f=>f.name);
if(!state.productMemory.length)rememberProducts(state.families.flatMap(f=>f.items));
drawProducts();render();renderDates();

function paperSize(){return $('#orientation').value==='landscape'?{width:297,height:210}:{width:210,height:297};}
function printableFamilies(){return state.families.filter(f=>f.printEnabled!==false).map(f=>({...f,items:f.items.filter(i=>i.printEnabled!==false)})).filter(f=>f.items.length);}
function renderPrintChoices(){$('#printChoices').innerHTML=state.families.filter(f=>f.items.length).map(f=>`<div class="print-choice"><label><input type="checkbox" data-print-family="${f.id}" ${f.printEnabled!==false?'checked':''}>${esc(f.name)} <small>${f.items.length}</small></label><details><summary>商品</summary>${f.items.map(i=>`<label><input type="checkbox" data-print-item="${i.id}" data-owner="${f.id}" ${i.printEnabled!==false?'checked':''}>${esc(ListCore.display(i.text))}</label>`).join('')}</details></div>`).join('');}
$('#printChoices').onchange=e=>{const el=e.target;const f=state.families.find(f=>f.id===(el.dataset.printFamily||el.dataset.owner));if(!f)return;if(el.dataset.printFamily){f.printEnabled=el.checked;f.items.forEach(i=>i.printEnabled=el.checked);renderPrintChoices();}else {const it=f.items.find(i=>i.id===el.dataset.printItem);if(it)it.printEnabled=el.checked;}save();makePreview();};
for(const [id,on] of [['selectAllPrint',true],['selectNonePrint',false]])$('#'+id).onclick=()=>{state.families.forEach(f=>{f.printEnabled=on;f.items.forEach(i=>i.printEnabled=on);});save();renderPrintChoices();makePreview();};
$('#orientation').onchange=makePreview;
$('#voiceEntry').onclick=()=>{const batch=document.querySelector('[data-mode="batch"]');batch.click();const input=$('#itemInput');input.focus({preventScroll:true});input.setSelectionRange(input.value.length,input.value.length);toast('请点手机键盘上的麦克风开始说话');};
document.addEventListener('click',e=>{document.querySelectorAll('.item-tools[open]').forEach(d=>{if(!d.contains(e.target))d.open=false;});});

$('#orderDate').onchange=e=>changeDate(e.target.value);
$('#todayDate').onclick=()=>changeDate(localDate());
$('#savedDates').onchange=e=>{if(e.target.value)changeDate(e.target.value);};
